### ISSUE TITLE
get more meaningful error messages

### ISSUE THREAD

**Issue by grenaud** [Juke34/ReadViewer#1]
Hello! Very nice tool, I used it for a slide.

Could I make a small feature request? Is it possible to use arbitrary spaces? I pasted a string and the message was something like "Does not look like SAM". Would it be possible to have a more meaningful error message? Also would it be possible to use any sort of space because sometimes the tabs don't carry over during the copy-paste.

**Comment by Juke34** [comment]
Thank you for using SamReadViewer

> Is it spossible to use arbitrary spaces?

Yes but I do not want to change the field separator because e.g. the space is a character valid in some fields. So I want to stick to the format definition and use only tabulation as delimiter. If the tabs are not carry over during the copy-paste it is more a problem of computer parameters.

If the tool become more known and this feature is requested many times I can think to add the feature.

For the error message I can update it to make something more meaningful.
